### ISSUE TITLE
mktemp template invalid on Ubuntu-based systems

### ISSUE THREAD

**Issue by twprogrammers** [skroll/privoxy-adblock#6]
I found this script when Googling around for an ABP to Privoxy solution and found that it bites the dust on the `mktemp` command, thus causing `dirname` and `rm` to fail with missing operands. Here is the error I got:
```
mktemp: too few X's in template ‘j’
```
I will post a patch to the code as a pull request in a couple minutes.

**Comment by Valinwolf** [comment]
Fixed in merged commit edd7c80
